/*!
 * SOURCE OF TRUTH KEYWORDS: tauri-specta builder, bindings export, src/bindings.ts, typed IPC, invoke handler, mount events, exported constants
 * WHAT:  Builds the tauri-specta builder that owns the IPC surface (commands, the registry event catalog and every
 *        IPC type) and, in tests, exports it to src/bindings.ts.
 * WHY:   One builder serves both the running app (invoke handler + event mounting) and the TS export, so the
 *        bindings can never describe a different surface than the app serves. The export runs as a `cargo test`
 *        (the gate runs cargo test before tsc), not at app startup, so a normal run never writes into src/.
 *        Types no command or event references yet are registered explicitly so the UI can import them today.
 *        Input limits the UI must validate against too (root CLAUDE.md §5) are exported as constants, so the Zod
 *        schema and the garde schema read one number.
 * WHERE: `builder()` is called by app::run; the export test writes src/bindings.ts (generated, never edited,
 *        excluded from lint, type-checked by tsc).
 */

use tauri::Runtime;
use tauri_specta::Builder;

use crate::{ipc, registry, types};

/**
 * SOURCE OF TRUTH KEYWORDS: builder, IPC surface, command catalog, registered types
 * WHAT:  The builder for runtime `R` with every command, event and IPC type registered.
 * WHY:   Commands are declared through ipc/factory.rs and listed by `ipc::commands::catalog`; events come from
 *        the registry catalog. The list of types mirrors types/mod.rs exports that cross IPC.
 * WHERE: app::run (Wry) and the export test below.
 */
pub fn builder<R: Runtime>() -> Builder<R> {
    Builder::<R>::new()
        .commands(ipc::commands::catalog())
        .events(registry::events::catalog())
        .typ::<types::AppError>()
        .typ::<types::AppErrorCode>()
        .typ::<types::SessionView>()
        .typ::<types::SessionUiInput>()
        .typ::<types::Transcript>()
        .typ::<types::TranscriptSummary>()
        .typ::<types::Page<types::TranscriptSummary>>()
        .typ::<types::SettingSpec>()
        .typ::<types::SettingValue>()
        .typ::<types::AsrCaps>()
        .typ::<types::AudioCaps>()
        .typ::<types::VadCaps>()
        .typ::<types::PolisherCaps>()
        .typ::<types::HotkeyCaps>()
        .typ::<types::InserterCaps>()
        .typ::<types::UpdaterCaps>()
        .typ::<types::EngineKind>()
        .typ::<types::EngineSpec>()
        .typ::<types::NavItem>()
        .typ::<types::HotkeySpec>()
        .typ::<types::MetricSpec>()
        .typ::<types::MetricsSummary>()
        .typ::<types::MetricUnit>()
        .typ::<types::ActivityDay>()
        .typ::<types::AudioDevice>()
        .typ::<types::ModelManifest>()
        .typ::<types::ModelStatus>()
        .typ::<types::UpdateStatus>()
        .typ::<types::PermissionState>()
        .typ::<types::HistoryChangeReason>()
        // 200 fits any integer type; the UI's search schema reads this instead of restating it.
        .constant(
            "HISTORY_SEARCH_MAX_CHARS",
            u32::try_from(types::HistoryListInput::MAX_SEARCH_CHARS).unwrap_or(u32::MAX),
        )
        .constant("HISTORY_PAGE_MAX", types::HistoryListInput::MAX_LIMIT)
}

/**
 * SOURCE OF TRUTH KEYWORDS: bindings export test, generate bindings.ts, typescript exporter, bindings header, IPC end-to-end test, mock runtime
 * WHAT:  Writes src/bindings.ts from `builder()` and checks the file carries the core IPC types; and calls a
 *        command through the served invoke handler on Tauri's mock runtime.
 * WHY:   This is the only generator of bindings.ts. Output is deterministic, so rerunning only changes the file
 *        when a Rust IPC type changed; tsc then fails on any UI code the change broke. The end-to-end call proves
 *        what factory tests cannot: the `echo_command!` output is registered, finds the managed CommandCtx and
 *        answers in the wire shape the bindings promise.
 * WHERE: `cargo test` (local gate), before `pnpm tsc --noEmit`.
 */
#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use specta_typescript::Typescript;
    use tauri::{
        WebviewWindowBuilder,
        ipc::{CallbackFn, InvokeBody},
        test::{
            INVOKE_KEY, MockRuntime, get_ipc_response, mock_builder, mock_context, noop_assets,
        },
        webview::InvokeRequest,
    };

    use super::builder;
    use crate::{
        ipc::testing,
        registry,
        types::{RegistryView, SettingEntry, SettingValue},
    };

    // Built from pieces so this Rust file does not itself show up as a bindings.ts header in `pnpm sot`.
    const HEADER: &str = concat!(
        "/**\n",
        " * SOURCE OF TRUTH KEYWORDS: bindings.ts, generated IPC bindings, tauri-specta, commands, events, AppError type\n",
        " * WHAT:  GENERATED by tauri-specta from the Rust types and commands. Never edit this file.\n",
        " * WHY:   The UI never hand-writes an IPC type; change the Rust type in src-tauri/src/types/ instead.\n",
        " * WHERE: Regenerated by `cargo test` (src-tauri/src/app/bindings.rs); imported as `@/bindings`.\n",
        " */",
    );

    #[test]
    fn exports_typescript_bindings() {
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/bindings.ts");
        builder::<tauri::Wry>()
            .export(Typescript::new().header(HEADER), &path)
            .expect("bindings export succeeds");

        let bindings = std::fs::read_to_string(&path).expect("bindings file is readable");
        for expected in [
            "export type AppError",
            "export type SessionView",
            "export type SettingSpec",
            "export type EngineSpec",
            "export type NavItem",
            "export type MetricSpec",
            "export type Page<",
            "sessionStateChanged",
            "registryGet",
            "export type RegistryView",
            "settingsGetAll",
            "settingsSet",
            "settingsReset",
            "export type SettingEntry",
            "export type SettingsSetInput",
            "export type SettingsResetInput",
            "appearanceGet",
            "appearanceChanged",
            "export type AppearanceView",
        ] {
            assert!(
                bindings.contains(expected),
                "bindings.ts is missing `{expected}`"
            );
        }
    }

    /// A mock app serving the real invoke handler over a test CommandCtx, and its main webview.
    fn mock_app() -> (tauri::App<MockRuntime>, tauri::WebviewWindow<MockRuntime>) {
        let ipc = builder::<MockRuntime>();
        let app = mock_builder()
            .manage(testing::ctx())
            .invoke_handler(ipc.invoke_handler())
            .build(mock_context(noop_assets()))
            .expect("the mock app builds");
        let webview = WebviewWindowBuilder::new(&app, "main", Default::default())
            .build()
            .expect("the mock window builds");
        (app, webview)
    }

    /// Invokes `cmd` with JSON `args` the way the generated bindings do.
    fn invoke(
        webview: &tauri::WebviewWindow<MockRuntime>,
        cmd: &str,
        args: serde_json::Value,
    ) -> Result<tauri::ipc::InvokeResponseBody, serde_json::Value> {
        get_ipc_response(
            webview,
            InvokeRequest {
                cmd: cmd.into(),
                callback: CallbackFn(0),
                error: CallbackFn(1),
                url: "http://tauri.localhost".parse().expect("valid url"),
                body: InvokeBody::Json(args),
                headers: Default::default(),
                invoke_key: INVOKE_KEY.to_owned(),
            },
        )
    }

    #[test]
    fn registry_get_answers_through_the_served_invoke_handler() {
        let (_app, webview) = mock_app();
        let response =
            invoke(&webview, "registry_get", serde_json::json!({})).expect("registry_get succeeds");
        let view: RegistryView = response.deserialize().expect("a RegistryView");
        assert_eq!(view.settings, registry::settings::SETTINGS);
        assert_eq!(view.nav.len(), registry::nav::NAV.len());
    }

    #[test]
    fn settings_commands_answer_in_the_wire_shape_the_bindings_promise() {
        let (_app, webview) = mock_app();
        let set = invoke(
            &webview,
            "settings_set",
            serde_json::json!({ "input": { "key": "metrics.typing_wpm", "value": { "kind": "int", "value": 72 } } }),
        )
        .expect("settings_set succeeds");
        let entry: SettingEntry = set.deserialize().expect("a SettingEntry");
        assert_eq!(entry.value, SettingValue::Int(72));

        let all: Vec<SettingEntry> = invoke(&webview, "settings_get_all", serde_json::json!({}))
            .expect("settings_get_all succeeds")
            .deserialize()
            .expect("a list of SettingEntry");
        assert!(all.contains(&entry));

        let error = invoke(
            &webview,
            "settings_set",
            serde_json::json!({ "input": { "key": "metrics.typing_wpm", "value": { "kind": "int", "value": 1 } } }),
        )
        .expect_err("an out-of-range value is refused");
        assert_eq!(error["code"], "Validation");
        assert_eq!(error["field"], "metrics.typing_wpm");

        let reset: SettingEntry = invoke(
            &webview,
            "settings_reset",
            serde_json::json!({ "input": { "key": "metrics.typing_wpm" } }),
        )
        .expect("settings_reset succeeds")
        .deserialize()
        .expect("a SettingEntry");
        assert_eq!(reset.value, SettingValue::Int(40));
    }
}
