/**
 * SOURCE OF TRUTH KEYWORDS: bindings.ts, generated IPC bindings, tauri-specta, commands, events, AppError type
 * WHAT:  GENERATED by tauri-specta from the Rust types and commands. Never edit this file.
 * WHY:   The UI never hand-writes an IPC type; change the Rust type in src-tauri/src/types/ instead.
 * WHERE: Regenerated by `cargo test` (src-tauri/src/app/bindings.rs); imported as `@/bindings`.
 */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  The audio input devices Windows has right now, with the current default marked. */
	audioListDevices: () => typedError<AudioDevice[], AppError>(__TAURI_INVOKE("audio_list_devices")),
	/**  Listens to an input device (none = the Windows default) for `window_ms` and reports how it sounded. */
	audioTestLevel: (input: AudioTestLevelInput) => typedError<MicCheck, AppError>(__TAURI_INVOKE("audio_test_level", { input })),
	/**  The current take as the pill renders it; Idle when no take is running. */
	sessionGetState: () => typedError<SessionView, AppError>(__TAURI_INVOKE("session_get_state")),
	/**  Sends a pill input (`stop`, or `cancel` which acts as Esc) to the current take. */
	sessionInput: (input: SessionUiInput) => typedError<null, AppError>(__TAURI_INVOKE("session_input", { input })),
	/**  Transcribes a stored take again from its saved audio and returns its updated History row. */
	sessionRetry: (input: TranscriptInput) => typedError<TranscriptSummary, AppError>(__TAURI_INVOKE("session_retry", { input })),
	/**
	 *  Sets what the session rehearses while an Echo window has focus: `hotkey` reports presses without starting a
	 *  take (HotkeyRehearsed), `take` shows a take's text in Echo instead of pasting it, `off` ends it.
	 */
	sessionRehearse: (input: SessionRehearsal) => typedError<null, AppError>(__TAURI_INVOKE("session_rehearse", { input })),
	/**  One page of History, newest first: every listed take (not no-speech ones), or those whose text matches `search`. */
	historyList: (input: HistoryListInput) => typedError<Page<TranscriptSummary>, AppError>(__TAURI_INVOKE("history_list", { input })),
	/**  One take in full (both texts and every measurement). */
	historyGet: (input: TranscriptInput) => typedError<Transcript, AppError>(__TAURI_INVOKE("history_get", { input })),
	/**  Copies a take's text to the clipboard (kept out of Windows clipboard history). */
	historyCopy: (input: TranscriptInput) => typedError<null, AppError>(__TAURI_INVOKE("history_copy", { input })),
	/**  Deletes a take and its saved audio. */
	historyDelete: (input: TranscriptInput) => typedError<null, AppError>(__TAURI_INVOKE("history_delete", { input })),
	/**  Clears History: every take's text and audio are erased; the dashboard and streak keep counting them. */
	historyClear: () => typedError<null, AppError>(__TAURI_INVOKE("history_clear")),
	/**  Pastes the newest completed take into the focused app again (copies it when pasting is not possible). */
	historyPasteLast: () => typedError<DeliveryOutcome, AppError>(__TAURI_INVOKE("history_paste_last")),
	/**
	 *  Every dashboard summary metric over `range`, in dashboard order; a value is null when there is nothing
	 *  to compute it from yet.
	 */
	metricsSummary: (input: MetricsSummaryInput) => typedError<MetricsSummary, AppError>(__TAURI_INVOKE("metrics_summary", { input })),
	/**  Words and completed takes per local day for the last `days` days, today included, oldest first. */
	metricsActivity: (input: MetricsActivityInput) => typedError<ActivityDay[], AppError>(__TAURI_INVOKE("metrics_activity", { input })),
	/**  The speech engine's readiness and, once it is ready, the accelerator it runs on, why, and the timings. */
	engineStatus: () => typedError<SpeechEngineStatus, AppError>(__TAURI_INVOKE("engine_status")),
	/**  Forgets the remembered accelerator measurements of the selected engine; on automatic, measures again now. */
	engineRemeasure: () => typedError<null, AppError>(__TAURI_INVOKE("engine_remeasure")),
	/**
	 *  Every engine that runs a model, with its status, selection, what it is doing and any running transfer,
	 *  plus whether downloads may run now.
	 */
	modelsList: () => typedError<ModelsView, AppError>(__TAURI_INVOKE("models_list")),
	/**
	 *  Downloads a model (resuming an earlier partial download), verifies and installs it. Progress arrives as
	 *  ModelProgress events; `cancelled` when `models_cancel_download` stopped it.
	 */
	modelsDownload: (input: ModelInput) => typedError<ModelTransferOutcome, AppError>(__TAURI_INVOKE("models_download", { input })),
	/**  Stops the model's running download, import or check; the partial download is kept. */
	modelsCancelDownload: (input: ModelInput) => typedError<null, AppError>(__TAURI_INVOKE("models_cancel_download", { input })),
	/**
	 *  Asks for a folder, then copies, verifies and installs the model from it (works offline); `cancelled` when
	 *  the picker was closed.
	 */
	modelsImport: (input: ModelInput) => typedError<ModelTransferOutcome, AppError>(__TAURI_INVOKE("models_import", { input })),
	/**  Checks every file of the model against its SHA-256; `ModelCorrupt` when one does not match. */
	modelsVerify: (input: ModelInput) => typedError<ModelTransferOutcome, AppError>(__TAURI_INVOKE("models_verify", { input })),
	/**  Deletes a downloaded model and its partial download. */
	modelsRemove: (input: ModelInput) => typedError<null, AppError>(__TAURI_INVOKE("models_remove", { input })),
	/**
	 *  Makes an engine the one in use (its model must be installed); the new engine warms up while the old one
	 *  keeps serving, and a take in progress finishes on the old one.
	 */
	modelsSetActive: (input: EngineInput) => typedError<null, AppError>(__TAURI_INVOKE("models_set_active", { input })),
	/**  Where the pill's buttons are now, in the page's CSS pixels; an empty list when it shows none. */
	pillSetHitAreas: (input: PillHitAreas) => typedError<null, AppError>(__TAURI_INVOKE("pill_set_hit_areas", { input })),
	/**  The pill finished its exit animation. */
	pillExited: () => typedError<null, AppError>(__TAURI_INVOKE("pill_exited")),
	/**  Every registry list the UI renders from. Compiled in, so it never changes while the app runs. */
	registryGet: () => typedError<RegistryView, AppError>(__TAURI_INVOKE("registry_get")),
	/**  What the Settings page may offer now: the caps requirements that hold and every choice setting's options. */
	settingsAvailability: () => typedError<SettingsAvailability, AppError>(__TAURI_INVOKE("settings_availability")),
	/**  Every setting's effective value (the stored value, or the registry default), ordered by key. */
	settingsGetAll: () => typedError<SettingEntry[], AppError>(__TAURI_INVOKE("settings_get_all")),
	/**
	 *  Stores a new value for a setting after checking it against the setting's registry spec and what this PC
	 *  supports; returns the value now in effect and emits SettingsChanged.
	 */
	settingsSet: (input: SettingsSetInput) => typedError<SettingEntry, AppError>(__TAURI_INVOKE("settings_set", { input })),
	/**  Returns a setting to its registry default; returns the value now in effect and emits SettingsChanged. */
	settingsReset: (input: SettingsResetInput) => typedError<SettingEntry, AppError>(__TAURI_INVOKE("settings_reset", { input })),
	/**  The theme, transparency and backdrop both windows paint from right now. */
	appearanceGet: () => typedError<AppearanceView, AppError>(__TAURI_INVOKE("appearance_get")),
	/**  Shows the folder that holds Echo's local log files. */
	appOpenLogsDir: () => typedError<null, AppError>(__TAURI_INVOKE("app_open_logs_dir")),
	/**  Opens the Windows privacy page where microphone access for desktop apps is turned on. */
	appOpenMicPrivacySettings: () => typedError<null, AppError>(__TAURI_INVOKE("app_open_mic_privacy_settings")),
	/**  Brings the main window forward on a page (the pill's "Set up" and "Open"). */
	appOpenPage: (input: OpenPageInput) => typedError<null, AppError>(__TAURI_INVOKE("app_open_page", { input })),
	/**
	 *  Whether onboarding is due now, the steps to walk, the speech engine and its model's state, and the Windows
	 *  microphone consent.
	 */
	onboardingGet: () => typedError<OnboardingView, AppError>(__TAURI_INVOKE("onboarding_get")),
	/**  Remembers that onboarding was finished, turns the session rehearsal off and returns the view now in effect. */
	onboardingComplete: () => typedError<OnboardingView, AppError>(__TAURI_INVOKE("onboarding_complete")),
	/**  Brings the main window forward on onboarding (the pill's "Set up"). */
	onboardingOpen: () => typedError<null, AppError>(__TAURI_INVOKE("onboarding_open")),
};

/** Events */
export const events = {
	appearanceChanged: makeEvent<AppearanceChanged>("AppearanceChanged"),
	audioDevicesChanged: makeEvent<AudioDevicesChanged>("AudioDevicesChanged"),
	audioLevel: makeEvent<AudioLevel>("AudioLevel"),
	historyChanged: makeEvent<HistoryChanged>("HistoryChanged"),
	hotkeyRehearsed: makeEvent<HotkeyRehearsed>("HotkeyRehearsed"),
	metricsChanged: makeEvent<MetricsChanged>("MetricsChanged"),
	modelProgress: makeEvent<ModelProgress>("ModelProgress"),
	modelsChanged: makeEvent<ModelsChanged>("ModelsChanged"),
	navigationRequested: makeEvent<NavigationRequested>("NavigationRequested"),
	onboardingRequested: makeEvent<OnboardingRequested>("OnboardingRequested"),
	sessionStateChanged: makeEvent<SessionStateChanged>("SessionStateChanged"),
	settingsChanged: makeEvent<SettingsChanged>("SettingsChanged"),
	transcriptSaved: makeEvent<TranscriptSaved>("TranscriptSaved"),
};

/* Constants */
export const HISTORY_PAGE_MAX = 500 as const;

export const HISTORY_SEARCH_MAX_CHARS = 200 as const;

export const MIC_CHECK_MAX_WINDOW_MS = 5000 as const;

export const MIC_CHECK_MIN_WINDOW_MS = 1000 as const;

export const SETTING_TOKEN_MAX_CHARS = 128 as const;

/* Types */
/**  Where inference runs. `gpu` means any DX12 adapter (DirectML), not one vendor. */
export type Accelerator = "cpu" | "gpu";

/**
 *  One measurement of an engine on this machine: the timing of every accelerator that ran (a GPU that could not
 *  start has none) and the accelerator it chose.
 */
export type AcceleratorBenchmark = {
	chosen: Accelerator,
	timings: AcceleratorTiming[],
	measured_at: UnixMs,
};

/**  Where the loaded speech engine runs, why, and what that was based on. */
export type AcceleratorChoice = {
	engine_id: EngineId,
	/**  The accelerator in use. */
	accelerator: Accelerator,
	reason: AcceleratorReason,
	/**  The GPU that was considered (in use when `accelerator` is `gpu`); None when none was looked for or found. */
	gpu: GpuAdapter | null,
	/**  This load's own timing. */
	bring_up: BringUpTiming,
	/**  The measurement `auto` decided from (made now or remembered); None for a fixed choice. */
	benchmark: AcceleratorBenchmark | null,
};

/**  Why the engine runs where it does. */
export type AcceleratorReason = 
/**  The engine declares one accelerator; there was nothing to choose. */
{ kind: "only_option" } | 
/**  The user picked this accelerator in Settings. */
{ kind: "preference" } | 
/**  The GPU was wanted but this PC has no DirectX 12 GPU. */
{ kind: "no_gpu" } | 
/**  The GPU was wanted but could not start or run the model; the CPU took over (05 A6). */
{ kind: "gpu_failed" } | 
/**  Automatic: runs on the CPU while the GPU is measured in the background (first start on this GPU and driver). */
{ kind: "measuring" } | 
/**  Automatic: both were measured just now and this one was faster. */
{ kind: "measured" } | 
/**  Automatic: the measurement made earlier for this GPU and driver was reused. */
{ kind: "remembered" } | 
/**  The GPU stopped working during a take (driver reset, device removed); the CPU took over for this run. */
{ kind: "gpu_lost" };

/**  How long one accelerator took on one engine, in ms. */
export type AcceleratorTiming = {
	accelerator: Accelerator,
	/**  Opening the model on it. */
	load_ms: number,
	/**  The first inference (05 A8), which includes one-time graph and shader compilation. */
	warm_up_ms: number,
	/**  The best steady-state inference on the benchmark audio: what a take feels. */
	run_ms: number,
};

/**  Words and completed takes on one local calendar day. */
export type ActivityDay = {
	/**  Local date, `YYYY-MM-DD`. */
	date: string,
	words: number,
	transcriptions: number,
};

/**  The only error type that crosses IPC. The variant name is the stable wire `code`. */
export type AppError = { code: "Validation"; field: string; message: string } | { code: "PermissionDenied"; permission: Permission } | { code: "Busy" } | { code: "NotFound"; resource: ResourceKind } | { code: "ModelMissing"; model_id: ModelId } | { code: "ModelCorrupt"; model_id: ModelId } | { code: "AudioDevice" } | { code: "Asr" } | { code: "Polish" } | { code: "Storage" } | { code: "Offline" } | { code: "Network" } | { code: "Hotkey"; reason: HotkeyIssue } | { code: "Internal" };

/**  The stable code of an AppError variant, without its fields. */
export type AppErrorCode = "Validation" | "PermissionDenied" | "Busy" | "NotFound" | "ModelMissing" | "ModelCorrupt" | "AudioDevice" | "Asr" | "Polish" | "Storage" | "Offline" | "Network" | "Hotkey" | "Internal";

/**  The theme, transparency or backdrop changed; carries the full view, so windows never merge partial updates. */
export type AppearanceChanged = AppearanceView;

/**  Everything the UI needs to theme both windows. */
export type AppearanceView = {
	theme: ThemePreference,
	transparency: Transparency,
	/**  The main window's backdrop; the pill is always transparent with CSS glass (05 W16). */
	backdrop: Backdrop,
};

/**  Caps of an `AsrEngine` adapter. */
export type AsrCaps = {
	languages: Language[],
	/**  The engine detects the spoken language itself. */
	auto_language: boolean,
	/**  Output already carries punctuation. */
	punctuation: boolean,
	/**  Output already carries sentence casing, so the rule polisher skips its casing stage. */
	casing: boolean,
	accelerators: Accelerator[],
	/**  Longest audio segment the engine accepts in one `transcribe` call, in seconds. */
	max_segment_s: number,
};

/**  Whether a take started now could be transcribed, and by which engine. */
export type AsrReadiness = 
/**  No engine is loaded and none is loading. */
{ kind: "unloaded" } | 
/**  `engine_id` is loading and warming up; segments wait for it. */
{ kind: "loading"; engine_id: EngineId } | 
/**  `engine_id` is loaded, warm and running on `accelerator`. */
{ kind: "ready"; engine_id: EngineId; accelerator: Accelerator } | 
/**  `engine_id` could not be loaded (e.g. `ModelMissing`); segments fail with this error. */
{ kind: "failed"; engine_id: EngineId; error: AppError };

/**  Caps of an `AudioCapture` adapter. */
export type AudioCaps = {
	/**  Device sample rates the adapter can open, in Hz. */
	sample_rates: number[],
	/**  Channel counts the adapter can open. */
	channels: number[],
};

/**  An audio input device the user can pick in Settings. */
export type AudioDevice = {
	id: AudioDeviceId,
	/**  Name as Windows shows it, e.g. `Microphone (USB Audio)`. */
	name: string,
	/**  Windows currently uses this device as the default input. */
	is_default: boolean,
	/**  How the device is connected. */
	transport: AudioTransport,
};

/**  Stable id of an audio input device as its capture adapter reports it; stored by `audio.input_device`. */
export type AudioDeviceId = string;

/**
 *  The microphones Windows offers changed (plugged, unplugged, enabled, disabled, a new default); device lists
 *  should refetch. Sent only when the list really differs, never once per raw Windows notice.
 */
export type AudioDevicesChanged = Record<string, never>;

/**  Input level while a take records or a microphone check listens (`audio_test_level`), at most 30 Hz. */
export type AudioLevel = {
	/**  Root mean square of the last frame, 0 to 1. */
	rms: number | null,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: AudioTestLevelInput, audio_test_level input, microphone check window, garde schema
 *  * WHAT:  The input of `audio_test_level`: which device to listen to (None = the Windows default) and for how long.
 *  * WHY:   Settings tests a device before it is saved and onboarding tests the default, so the device is an input,
 *  *        not the stored setting. The factory enforces the window bounds and the device id shape before the mic
 *  *        opens (02 §4.1); whether the device is present is the adapter's answer. The window starts at 1 s because a
 *  *        device's first half second can be driver warm-up silence (05 W34).
 *  * WHERE: ipc/commands/audio.rs; built in the UI through the generated bindings.
 *  
 */
export type AudioTestLevelInput = {
	device: AudioDeviceId | null,
	/**  How long to listen, in ms. */
	window_ms: number,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: AudioTransport, microphone connection, Bluetooth microphone, USB microphone, built-in microphone, virtual audio device
 *  * WHAT:  How an input device reaches the PC.
 *  * WHY:   A Bluetooth headset switches profile when its microphone opens and cuts the first 0.5–2 s (05 W11), so the
 *  *        pipeline must know the transport of the device a take opened to warn once; the Settings picker and
 *  *        onboarding can show it too. Unknown connections are `Other`, never guessed.
 *  * WHERE: AudioDevice.transport (audio_list_devices), CaptureStream::transport (the device a take opened);
 *  *        decided by the capture adapter.
 *  
 */
export type AudioTransport = 
/**  The PC's own audio hardware (integrated chipset or an internal card). */
"built_in" | "usb" | "bluetooth" | 
/**  Software routing (a virtual cable, a meeting app's device). */
"virtual" | "other";

/**  What is behind the main window's content. */
export type Backdrop = 
/**  Native Mica (Windows 11 with transparency on); the page paints no background of its own. */
"mica" | 
/**  No native material: the page paints `--color-bg`. */
"solid";

/**  Loading and warming the engine on the accelerator it runs on now, in ms. */
export type BringUpTiming = {
	load_ms: number,
	warm_up_ms: number,
};

/**  A size or transfer amount in bytes. */
export type ByteCount = number;

/**  A capability the active adapters must declare for a setting or option to be shown. */
export type CapsRequirement = 
/**  The active ASR engine lists `gpu` in `AsrCaps.accelerators`. */
"gpu_accelerator" | 
/**  The active ASR engine lists more than one language. */
"multiple_languages" | 
/**  The hotkey adapter reports key-up (`HotkeyCaps.supports_release`), needed for hold-to-talk. */
"hotkey_release" | 
/**  The updater adapter reports `UpdaterCaps.available`. */
"updater_available";

/**  How a finished take reached the user. */
export type DeliveryOutcome = 
/**  Pasted into the target app (and kept on the clipboard if the setting is on). */
"pasted" | 
/**  Only copied: the target could not receive a paste (elevated window, 05 W2) or auto-paste is off. */
"copied" | 
/**  VAD heard no speech; nothing was pasted (02 §6.1, 05 A4). */
"no_speech" | 
/**
 *  A rehearsed take (onboarding's practice take): the text stays in Echo for the window that asked for the
 *  rehearsal to show; neither the clipboard nor any app was touched.
 */
"shown";

/**  The caps a registry engine entry declares, tagged by the kind of engine it builds. */
export type EngineCaps = {
	kind: "asr",
} & AsrCaps | {
	kind: "polisher",
} & PolisherCaps | {
	kind: "vad",
} & VadCaps;

/**  Registry id of an engine entry (ASR, polisher or VAD), kebab-case, e.g. `parakeet-tdt-0.6b-v3`. */
export type EngineId = string;

export type EngineInput = {
	engine_id: EngineId,
};

/**  What an engine registry entry builds. */
export type EngineKind = "asr" | "polisher" | "vad";

/**  What a selected engine is doing now. */
export type EngineRuntime = 
/**  Its model is loading and warming up. */
{ kind: "loading" } | 
/**  Loaded and warm; `accelerator` when the engine runs on one (speech engines). */
{ kind: "ready"; accelerator: Accelerator | null } | 
/**  It could not be loaded; takes fail with `error` until it is fixed (e.g. `ModelCorrupt`). */
{ kind: "failed"; error: AppError };

/**  How an engine comes to be used. */
export type EngineSelection = 
/**  Used on every take whenever it is installed (a bundled detector); there is nothing to choose. */
{ kind: "built_in" } | 
/**  Chosen by a setting (`models_set_active` writes it); `active` when the settings select it now. */
{ kind: "selectable"; active: boolean };

/**  What the UI (Models page, Settings options) knows about a registry engine entry. */
export type EngineSpec = {
	id: EngineId,
	label: string,
	/**  The model manifest the engine runs, when it needs one. */
	model_id: ModelId | null,
	caps: EngineCaps,
};

/**  One choice of an `Enum` setting. */
export type EnumOption = {
	/**  Stored value. */
	value: string,
	label: string,
	/**  The option is hidden unless the requirement holds. */
	requires: CapsRequirement | null,
};

/**  The options of an `Enum` setting: a fixed list, or a source resolved at runtime by the registry. */
export type EnumOptions = { from: "fixed"; list: EnumOption[] } | { from: "runtime"; source: OptionSource };

/**  A hardware graphics adapter that can run DirectX 12 compute (what DirectML needs). */
export type GpuAdapter = {
	/**  Position in the DXGI adapter enumeration: the device index DirectML opens. Not stable across hot-plug. */
	ordinal: number,
	/**  The name the driver reports, e.g. `Intel(R) UHD Graphics`. */
	name: string,
	/**  PCI vendor id (0x10DE NVIDIA, 0x1002 AMD, 0x8086 Intel). */
	vendor_id: number,
	/**  PCI device id. */
	device_id: number,
	/**  The user-mode driver version, e.g. `32.0.101.7076`. */
	driver_version: string,
	/**  Memory on the card itself; 0 or small on integrated GPUs, which share system memory. */
	dedicated_memory: ByteCount,
};

/**  Why the history list changed. */
export type HistoryChangeReason = "inserted" | "updated" | "deleted" | 
/**  Startup recovery marked unfinished takes recoverable. */
"recovered" | 
/**  A retention sweep removed audio or rows. */
"retention" | 
/**  The user cleared History: its takes were erased and hidden, their measurements kept. */
"cleared";

/**  History rows changed; list queries should refetch. */
export type HistoryChanged = {
	reason: HistoryChangeReason,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: HistoryListInput, history_list input, search query, cursor, page size, garde schema
 *  * WHAT:  The input of `history_list`: an optional full-text search, the cursor of the page to continue after (None
 *  *        = the newest page) and how many rows to return.
 *  * WHY:   The factory enforces the declared bounds before the handler runs (02 §4.1): a search longer than
 *  *        MAX_SEARCH_CHARS or a page outside 1..=MAX_LIMIT is a Validation error on its field, so the service never
 *  *        builds a huge FTS query or reads an unbounded page. Blank search text means "no search" (the service turns
 *  *        text with no letters or digits into an empty page, so the command normalizes blanks first). Whether the
 *  *        cursor is one the service produced is the service's answer (`Validation { cursor }`).
 *  * WHERE: ipc/commands/history.rs; built in the UI by the history list query (src/hooks/use-history.ts).
 *  
 */
export type HistoryListInput = {
	search: string | null,
	cursor: PageCursor | null,
	limit: number,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: HotkeyAction, hotkey action, record action, cancel take action, paste last action, hotkey routing
 *  * WHAT:  What pressing (and releasing) a registry hotkey does: start or stop a take, cancel it with the Esc
 *  *        countdown, or paste the last transcript.
 *  * WHY:   The session actor turns a HotkeyEvent into a session input by the action its registry entry declares, so
 *  *        a new hotkey that reuses an action is one registry entry, and a new action fails to compile until the
 *  *        actor says what it does. The actor binds only the Always-scoped hotkeys whose action it handles, so a
 *  *        combination is never taken from other apps while pressing it would do nothing.
 *  * WHERE: HotkeySpec.action (registry/hotkeys.rs); read by the session actor (pipeline/session/hotkey_input.rs)
 *  *        through registry::hotkeys::find.
 *  
 */
export type HotkeyAction = 
/**  Starts a take, or stops it (toggle mode); in hold mode the release stops it. */
"record" | 
/**  The Esc countdown: a first press pauses and counts down, a second one undoes (05 W10). */
"cancel_take" | 
/**  Pastes the most recent delivered transcript again. */
"paste_last";

/**  Caps of a `HotkeyService` adapter. */
export type HotkeyCaps = {
	/**  Key-up events are reported, so hold-to-talk is possible. */
	supports_release: boolean,
	/**  A combination of modifiers alone (e.g. Ctrl+Alt) can be bound. */
	supports_modifier_only: boolean,
};

/**  Registry id of a hotkey binding, kebab-case, e.g. `record`, `paste-last`, `cancel`. */
export type HotkeyId = string;

/**  Why a hotkey could not be registered. */
export type HotkeyIssue = 
/**
 *  The combination is already taken: by another Echo hotkey, or (with a RegisterHotKey backend) by another app
 *  (05 W7).
 */
"conflict" | 
/**  The combination cannot be registered (no key, or not allowed by the hotkey adapter's caps). */
"invalid";

/**
 *  A hotkey was pressed, released or interrupted while the session rehearses hotkeys (`session_rehearse`) in an
 *  Echo window; it started nothing. Onboarding's hotkey step shows it.
 */
export type HotkeyRehearsed = {
	hotkey: HotkeyId,
	/**  What the hotkey does outside a rehearsal. */
	action: HotkeyAction,
	state: KeyState,
};

/**  When a hotkey is registered with the system. */
export type HotkeyScope = 
/**  From startup until exit. */
"always" | 
/**  Only while a take is recording or counting down to cancel. */
"during_session";

/**  A registry hotkey entry. */
export type HotkeySpec = {
	id: HotkeyId,
	label: string,
	default_accelerator: Shortcut,
	/**  The Hotkey setting the user rebinds it with; None when the combination is fixed. */
	setting_key: SettingKey | null,
	scope: HotkeyScope,
	/**  What pressing it does. */
	action: HotkeyAction,
};

/**  Caps of a `TextInserter` adapter. */
export type InserterCaps = {
	/**  Can paste into windows running at a higher integrity level than Echo (05 W2). */
	can_target_elevated: boolean,
	/**  Inserts by pasting what the clipboard holds, so delivery writes the text to the clipboard first. */
	uses_clipboard: boolean,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: KeyState, Pressed, Released, Interrupted, modifier-only chord, chord interrupted, part of another shortcut
 *  * WHAT:  What happened to a bound combination: it went down, came back up, or turned out to be the start of a
 *  *        longer shortcut (Interrupted).
 *  * WHY:   A modifier-only combination such as Ctrl+Alt fires the moment it is held (hold-to-talk must not wait), but
 *  *        the same keys start other apps' shortcuts (Ctrl+Alt+T, Ctrl+Alt+Del). When another key joins while it is
 *  *        held, the adapter reports Interrupted instead of Released, so the session can drop a take that was never
 *  *        meant (05 W9). Only adapters with `HotkeyCaps.supports_modifier_only` report it; after Interrupted no
 *  *        Released follows for that press.
 *  *        It crosses IPC inside HotkeyRehearsed, so onboarding can show a press, a release or an interruption.
 *  * WHERE: HotkeyEvent.state, built by the hotkey adapters; mapped to session inputs by
 *  *        pipeline/session/hotkey_input.rs; reported as-is by a hotkey rehearsal (pipeline/session/rehearsal.rs).
 *  
 */
export type KeyState = "pressed" | "released" | 
/**  Another key joined a held modifier-only combination: the press was part of another shortcut. */
"interrupted";

/**
 *  A spoken-language code (ISO 639-1, e.g. `en`, `de`). "Auto-detect" is not a language; it is the absence
 *  of one (`Option<Language>`), offered only when `AsrCaps.auto_language` is set.
 */
export type Language = string;

/**  Which spoken languages a component handles. */
export type LanguageSupport = { kind: "any" } | { kind: "only"; languages: Language[] };

/**  How much latency a polisher adds to delivery. */
export type LatencyClass = 
/**  Milliseconds; always safe on the delivery path. */
"instant" | 
/**  Hundreds of milliseconds; must run under a timeout with a fallback (02 §8.3). */
"slow";

/**  The SQL aggregate behind a metric (formulas in 02 §7.4). */
export type MetricAggregate = "words" | "transcriptions" | "time_saved" | "speaking_wpm" | "median_latency" | "streak";

/**  Where a metric sits on the dashboard (04 §5). */
export type MetricEmphasis = 
/**  The one large card at the top. */
"hero" | 
/**  A regular stat card, or the activity chart for an `activity` query. */
"primary" | 
/**  A small card below the chart. */
"secondary";

/**  Registry id of a dashboard metric, kebab-case, e.g. `time-saved`. */
export type MetricId = string;

/**  What a metric reads. */
export type MetricQuery = 
/**  One value of `metrics_summary(range)`. */
{ kind: "summary"; aggregate: MetricAggregate } | 
/**  Words per day for the last `days` days, from `metrics_activity(days)`. */
{ kind: "activity"; days: number };

/**  A registry metric entry. */
export type MetricSpec = {
	id: MetricId,
	label: string,
	/**  One sentence on how the value is computed, shown as the card's tooltip. */
	help: string,
	unit: MetricUnit,
	query: MetricQuery,
	emphasis: MetricEmphasis,
};

/**  How a metric value is formatted. */
export type MetricUnit = 
/**  Milliseconds shown as a human duration (e.g. `2 h 5 min`). */
"duration" | "count" | "wpm" | 
/**  Milliseconds shown as-is (latency). */
"ms" | "days";

export type MetricValue = {
	aggregate: MetricAggregate,
	/**
	 *  None when there is nothing to compute it from yet (no completed take in the range, no speech time, no
	 *  latency), so the UI can tell "no data" from zero.
	 */
	value: number | null,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: MetricsActivityInput, metrics_activity input, activity days, chart length, garde schema
 *  * WHAT:  The input of `metrics_activity`: how many local calendar days, today included, the series covers.
 *  * WHY:   The factory enforces 1..=MAX_DAYS before the handler runs (02 §4.1), so the series is never empty and
 *  *        never an unbounded allocation; a year and a day covers any chart the dashboard could draw. The UI reads
 *  *        the days from the registry's activity metric (`MetricQuery::Activity { days }`), never its own number.
 *  * WHERE: ipc/commands/metrics.rs; built in the UI by the dashboard activity query (src/hooks/use-metrics.ts).
 *  
 */
export type MetricsActivityInput = {
	days: number,
};

/**  Dashboard aggregates changed; metric queries should refetch. */
export type MetricsChanged = Record<string, never>;

/**  The window a summary covers, ending now: whole local calendar days counted back from today, or every kept take. */
export type MetricsRange = "today" | "last_7_days" | "last_30_days" | "all_time";

export type MetricsSummary = {
	range: MetricsRange,
	values: MetricValue[],
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: MetricsSummaryInput, metrics_summary input, dashboard range, summary window
 *  * WHAT:  The input of `metrics_summary`: which MetricsRange to compute over.
 *  * WHY:   A struct, not a bare enum, so the command can grow options (a comparison window for trends) without
 *  *        changing its call sites, like every other command input. serde already refuses an unknown range (the
 *  *        factory maps that to `Validation`, 05 W27), so garde has nothing left to check.
 *  * WHERE: ipc/commands/metrics.rs; built in the UI by the dashboard summary query (src/hooks/use-metrics.ts).
 *  
 */
export type MetricsSummaryInput = {
	range: MetricsRange,
};

/**  The result of `audio_test_level`: levels over the test window and what they mean. */
export type MicCheck = {
	/**  Loudest RMS over any level window, 0 to 1. */
	peak_rms: number | null,
	/**  RMS over the whole window, 0 to 1. */
	mean_rms: number | null,
	verdict: MicVerdict,
};

/**  How a microphone check sounded. */
export type MicVerdict = 
/**  Digital silence: the device delivers nothing (muted, or blocked by Windows privacy, 05 W13). */
"no_signal" | 
/**  Some sound, but too quiet for reliable recognition. */
"too_quiet" | "good" | 
/**  So loud that speech clips. */
"too_loud";

/**  One card of the Models page: an engine that runs a model, and everything the card shows or offers. */
export type ModelEntry = {
	engine: EngineSpec,
	model: ModelManifest,
	/**  The manifests the model needs to run (its runtime), installed with it, in install order. */
	requires: ModelManifest[],
	/**  What a download of the model and everything it requires moves (the card's size). */
	download_bytes: ByteCount,
	/**
	 *  The model and its requirements together: `Installed` only when all are; a missing requirement makes an
	 *  installed model `Partial` (the next download fetches only what is missing), a damaged one `Corrupt`.
	 */
	status: ModelStatus,
	selection: EngineSelection,
	/**  What the engine is doing, when the settings select it and it has been asked to load. */
	runtime: EngineRuntime | null,
	/**  The download, import or check running for this model now, with its latest progress. */
	transfer: ModelProgress | null,
};

/**  One file of a model. */
export type ModelFile = {
	/**  File name inside the model folder, e.g. `encoder-model.int8.onnx`; never a path with separators. */
	name: string,
	/**  Where it is downloaded from; for a bundled model, the upstream it was taken from. */
	url: string,
	sha256: Sha256Hex,
	bytes: ByteCount,
};

/**  Registry id of a model manifest, kebab-case. */
export type ModelId = string;

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: ModelInput, EngineInput, models command input, model id input, engine id input
 *  * WHAT:  The input of the models commands that act on one model (download, cancel, import, verify, remove) and of
 *  *        `models_set_active` (one engine).
 *  * WHY:   A struct, not a bare id, so a command can grow options without changing its call sites. The declared schema
 *  *        (garde) refuses an id that could not be a registry id before any lookup; whether it is registered is the
 *  *        registry's answer (`NotFound { model | engine }`).
 *  * WHERE: ipc/commands/models.rs; built in the UI by the Models page actions.
 *  
 */
export type ModelInput = {
	model_id: ModelId,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: ModelKind, model or runtime, runtimes folder, sidecar runtime manifest, install root
 *  * WHAT:  What a manifest installs: model weights an engine loads, or a runtime program an engine runs as a
 *  *        sidecar (llama-server).
 *  * WHY:   Both are pinned, hashed downloads through the same model manager (02 §8.2), but they live in different
 *  *        folders (`models/<id>/` and `runtimes/<id>/`, 02 §7.1) and a runtime can serve several models, so the
 *  *        kind is data on the manifest and AppPaths turns it into the folder; nothing branches on a model's name.
 *  * WHERE: ModelManifest; AppPaths::install_dir and the ModelStore adapter's layout.
 *  
 */
export type ModelKind = 
/**  Weights an engine loads, installed in `models/<id>/`. */
"model" | 
/**  A program an engine starts as a sidecar, installed in `runtimes/<id>/`. */
"runtime";

/**  Everything needed to fetch, verify and credit a model. */
export type ModelManifest = {
	id: ModelId,
	label: string,
	kind: ModelKind,
	/**  SPDX license id, e.g. `CC-BY-4.0`, listed in About → Models & licenses (05 A15). */
	license: string,
	/**  Credit line the license requires; None when it requires none. */
	attribution: string | null,
	/**  Upstream revision (commit hash, or the release tag of a runtime) the digests were computed from. */
	revision: string,
	/**  The installed files, each with the size and digest it has on disk. */
	files: ModelFile[],
	/**
	 *  When set, `files` are not fetched one by one: this one archive (a zip) is downloaded and verified, and only
	 *  the listed files are unpacked from it (each checked against its own digest); the archive itself is not kept.
	 */
	archive: ModelFile | null,
	/**
	 *  Other manifests this one needs installed to run (the runtime an LLM runs on); the model manager downloads,
	 *  imports, checks and counts them together with this one, requirements first.
	 */
	requires: ModelId[],
	/**  Ships inside the installer's resources, so it is never downloaded. */
	bundled: boolean,
};

export type ModelPhase = 
/**  Bytes are arriving from the network or being copied from the chosen folder. */
"transferring" | 
/**  The connection dropped; the download resumes from where it stopped after a short wait. */
"waiting" | 
/**  SHA-256 of every file is being checked. */
"verifying" | 
/**  Verified files are being moved into `models/<id>/`. */
"installing" | 
/**  The model is installed and usable. */
"ready" | "cancelled" | "failed";

/**
 *  Progress of a model download, import or check, at most 10 Hz; a terminal phase (ready, cancelled, failed) ends
 *  the stream.
 */
export type ModelProgress = {
	model_id: ModelId,
	bytes: ByteCount,
	total: ByteCount,
	phase: ModelPhase,
};

/**  Whether a model is on disk and usable. */
export type ModelStatus = { kind: "not_installed" } | 
/**  An interrupted download left `bytes` in the `.partial` folder; the next download resumes from there. */
{ kind: "partial"; bytes: ByteCount } | 
/**  Every file is in place with the manifest's size (hashes are checked on demand, 02 §8.2). */
{ kind: "installed" } | 
/**
 *  The installed files do not match the manifest: a size differs or a file is gone (the startup check), or a
 *  hash check failed since the model was installed. Downloading again replaces it.
 */
{ kind: "corrupt" };

/**  How a download or import ended when it did not fail. */
export type ModelTransferOutcome = 
/**  The model is installed and verified. */
"completed" | 
/**  The user stopped it (or closed the folder picker); a partial download is kept for the next try. */
"cancelled";

/**
 *  What the Models page shows changed: a model was installed, removed or found damaged, or the speech engine
 *  started, finished or failed loading; `models_list` should refetch.
 */
export type ModelsChanged = Record<string, never>;

/**  Everything the Models page renders. */
export type ModelsView = {
	/**  One entry per registry engine that runs a model, in registry order. */
	entries: ModelEntry[],
	/**  Whether downloads may run now (offline mode denies them); importing from a folder works either way. */
	network: PermissionState,
};

/**  A sidebar icon, serialized as its lucide-react name (e.g. `layout-dashboard`). */
export type NavIcon = "layout-dashboard" | "history" | "boxes" | "settings";

/**  Registry id of a sidebar navigation item; each one has a page in `src/routes/<id>/`. */
export type NavId = "dashboard" | "history" | "models" | "settings";

/**  A registry navigation entry. */
export type NavItem = {
	id: NavId,
	label: string,
	icon: NavIcon,
	/**  Router path, starting with `/`. */
	route: string,
	/**  Position in the sidebar, ascending; unique across entries. */
	order: number,
};

/**
 *  Something outside the main window's router (the pill's "Set up" or "Open") asked for a page; the main window
 *  navigates there. Sent after the main window was brought forward.
 */
export type NavigationRequested = {
	page: NavId,
};

/**  When a step is part of onboarding. */
export type OnboardingCondition = 
/**  Until onboarding has been completed once. */
"first_run" | 
/**  Whenever the selected speech engine's model is not ready (first run or later). */
"speech_model_missing" | 
/**  Every time onboarding is shown. */
"always";

/**
 *  Something outside the main window (the pill's "Model not installed · Set up") asked for onboarding; the main
 *  window opens it. Sent after the main window was brought forward.
 */
export type OnboardingRequested = Record<string, never>;

/**  One onboarding step; each has a component in `src/routes/onboarding/_components/`. */
export type OnboardingStepId = 
/**  Windows microphone consent, the privacy deep link and a live level meter. */
"microphone" | 
/**  Download or import the speech model. */
"model" | 
/**  Dictate with the hotkey into a practice pad in Echo (text shown, never pasted); rebind a clashing hotkey. */
"practice";

/**  A registry onboarding step. */
export type OnboardingStepSpec = {
	id: OnboardingStepId,
	/**  Short name for the dot indicator's accessible label, e.g. "Microphone". */
	label: string,
	/**  When the step is walked. */
	shown: OnboardingCondition,
	/**  The settings the step lets the user change on the spot, in order (rendered from their registry specs). */
	settings: SettingKey[],
};

/**  Everything the onboarding screen renders from. */
export type OnboardingView = {
	/**  Onboarding should be shown: it was never completed, or the speech model is not ready. */
	required: boolean,
	/**  Onboarding has never been completed. */
	first_run: boolean,
	/**  The speech engine the settings select (its Models card is the model step); None when none is registered. */
	speech_engine: EngineId | null,
	/**  The selected speech engine's model is installed and undamaged (true when it needs no model). */
	speech_model_ready: boolean,
	/**  Windows microphone consent for desktop apps; None when it could not be read. */
	microphone: PermissionState | null,
	/**  The dictation hotkey as it is bound now (for the practice step's instructions). */
	record_hotkey: Shortcut | null,
	/**  The dictation hotkey is held while speaking (hold mode); false: press to start, press again to stop. */
	hold_to_talk: boolean,
	/**  The steps to walk now, in order; empty when onboarding is not required. */
	steps: OnboardingStepSpec[],
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: OpenPageInput, app_open_page input, open main window on a page, pill Set up, pill Open
 *  * WHAT:  The input of `app_open_page`: which main-window page to show.
 *  * WHY:   The pill has no router and no rights on the main window (capabilities/pill.json), so its "Set up" and
 *  *        "Open" buttons ask Rust to bring the main window forward on a page; the page is a NavId, so only pages the
 *  *        registry has can be named, and serde already refuses anything else (nothing left for garde to check).
 *  * WHERE: ipc/commands/system.rs (`app_open_page`); sent by the pill (src/pill) and any surface without the router.
 *  
 */
export type OpenPageInput = {
	page: NavId,
};

/**  Where the options of an `Enum` setting come from when they depend on what is registered or installed. */
export type OptionSource = 
/**  Every registered engine of kind `asr`. */
"asr_engines" | 
/**  Registered polisher engines that need a model (the opt-in LLM stage; the always-on rule stages need none). */
"model_polishers" | 
/**  `auto` (when the selected ASR engine auto-detects) plus every language of that engine. */
"asr_languages" | 
/**  `auto` plus every accelerator of the selected ASR engine. */
"asr_accelerators";

/**  A rectangle on the pill's page, in whole CSS pixels from its top-left corner. */
export type OverlayRect = {
	x: number,
	y: number,
	width: number,
	height: number,
};

/**  A slice of a longer list, newest first unless the command says otherwise. */
export type Page<T> = {
	items: T[],
	/**  None when this is the last page. */
	next_cursor: PageCursor | null,
};

/**  Opaque position after the last item of a page; pass it back to fetch the next page. */
export type PageCursor = string;

export type Permission = 
/**  Windows microphone privacy consent for desktop apps. */
"microphone" | 
/**  Any outbound request; offline mode denies it. */
"network" | 
/**  Reading or writing the system clipboard. */
"clipboard" | 
/**  Sending synthetic input (the Ctrl+V paste) to the focused app. */
"input_injection";

/**  Whether a permission holds right now. */
export type PermissionState = "granted" | "denied";

/**  The pill's clickable rectangles; everything else passes clicks through. */
export type PillHitAreas = {
	areas: OverlayRect[],
};

/**  Caps of a `TextPolisher` adapter. */
export type PolisherCaps = {
	latency_class: LatencyClass,
	languages: LanguageSupport,
	/**  A model must be installed before the polisher can run. */
	needs_model: boolean,
};

/**  Every registry list the UI renders from. */
export type RegistryView = {
	settings: SettingSpec[],
	/**  Settings page sections in page order, with their headings. */
	sections: SettingSectionSpec[],
	hotkeys: HotkeySpec[],
	nav: NavItem[],
	engines: EngineSpec[],
	metrics: MetricSpec[],
};

/**  What a `NotFound` error could not find. */
export type ResourceKind = "transcript" | "model" | "engine" | "setting" | "audio_device" | 
/**  An update to install (the updater found none, or updates are not configured, 02 §11). */
"update" | 
/**  A take's WAV journal: retention deleted it, or it never reached the disk (retry needs it, 02 §7.3). */
"recording" | 
/**  A take's text: it was never transcribed, or it was empty (copy and paste-last need it). */
"transcript_text";

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: SessionRehearsal, session_rehearse, rehearsal mode, hotkey test, practice take, onboarding try it, keep text in Echo
 *  * WHAT:  What the session rehearses while Echo's own window has focus: nothing (Off), the hotkeys (every press is
 *  *        reported as HotkeyRehearsed and starts no take), or a take (it runs as usual, but its text stays in Echo,
 *  *        DeliveryOutcome::Shown, instead of being pasted or copied).
 *  * WHY:   Onboarding must prove the hotkey and the whole take work before the user relies on them (01 §7) without
 *  *        recording a test press or pasting into Echo itself. A rehearsal only ever applies while an Echo window is
 *  *        in the foreground, so one left on by a window that closed or hid can never swallow a hotkey or keep text
 *  *        from the app the user dictates into. It is session configuration, not recording state: the machine is
 *  *        untouched, the actor only decides what a hotkey or a delivery means (02 §5 stays the one owner).
 *  * WHERE: Sent by `session_rehearse` (ipc/commands/session.rs) from onboarding's practice step (`take`); held by
 *  *        the session actor (pipeline/session/rehearsal.rs).
 *  
 */
export type SessionRehearsal = 
/**  Hotkeys and takes behave normally. */
"off" | 
/**  Hotkey presses are reported (HotkeyRehearsed) and start nothing. */
"hotkey" | 
/**  Takes run fully and their text is shown in Echo instead of delivered. */
"take";

/**  The session changed state; carries the full view, so the UI never merges partial updates. */
export type SessionStateChanged = SessionView;

/**  Where a take is in its lifecycle (02 §5 diagram). */
export type SessionStatus = "idle" | 
/**  Hotkey pressed: the row is inserted and the mic is opening. */
"arming" | "recording" | 
/**  Esc pressed: capture paused while the cancel countdown runs. */
"cancel_pending" | 
/**  Capture stopped: the tail segment is being transcribed. */
"finalizing" | 
/**  The joined text is being polished and delivered to the clipboard and the target app. */
"delivering" | "done" | 
/**  The countdown elapsed: row and audio were deleted. */
"discarded" | 
/**  The take failed; its audio and row are kept for retry. */
"failed";

/**
 *  Session inputs the UI is allowed to send through `session_input`; every variant is valid as sent, so the
 *  factory's validation only checks the shape (serde already refused anything else).
 */
export type SessionUiInput = 
/**  The pill's stop button: same effect as pressing the record hotkey while recording. */
"stop" | 
/**
 *  The pill's cancel (✕) and undo buttons: same effect as pressing Esc, so the first press starts the cancel
 *  countdown and a second one before it runs out resumes the take.
 */
"cancel";

/**  Everything the UI may know about the current take. */
export type SessionView = {
	status: SessionStatus,
	/**  The take's row (from `Arming` on); None when no row exists (a missing model, a discarded take). */
	transcript_id: TranscriptId | null,
	/**  Recorded time so far, excluding time paused in `CancelPending`. */
	elapsed_ms: number,
	/**  Time left before a pending cancel discards the take. */
	countdown_remaining_ms: number | null,
	/**  Set when `status` is `Done`. */
	outcome: DeliveryOutcome | null,
	/**  Set when `status` is `Failed`. */
	error: AppError | null,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: SettingEntry, effective setting value, settings_get_all output, settings_set output
 *  * WHAT:  One setting's key with its effective value (stored value over the registry default).
 *  * WHY:   `settings_get_all` returns every effective value and `settings_set` / `settings_reset` return the value now
 *  *        in effect, so the UI replaces its query data with exactly what Rust holds instead of guessing.
 *  * WHERE: Output of the settings commands (ipc/commands/settings.rs).
 *  
 */
export type SettingEntry = {
	key: SettingKey,
	value: SettingValue,
};

/**  Registry key of a setting, `section.snake_key`, e.g. `output.auto_paste`. */
export type SettingKey = string;

/**  The control and the validation rule of a setting. */
export type SettingKind = { kind: "bool" } | 
/**  Inclusive range. */
{ kind: "int"; min: number; max: number; unit: SettingUnit | null } | { kind: "enum"; options: EnumOptions } | 
/**  A global shortcut accelerator such as `Ctrl+Alt+Space`; only the hotkey adapter parses it. */
{ kind: "hotkey" } | 
/**
 *  An audio input device id; no value means the system default device. Its options are the devices the
 *  capture adapter lists at runtime (`audio_list_devices`).
 */
{ kind: "device" } | { kind: "text"; max_len: number } | { kind: "pairs"; max_pairs: number; max_len: number };

/**  The choices an `Enum` setting offers right now. */
export type SettingOptions = {
	key: SettingKey,
	/**  Fixed options whose requirement holds, or the runtime source resolved now, in display order. */
	options: EnumOption[],
};

/**  The Settings page group a setting belongs to; equals the prefix of its key (`general.theme` → `general`). */
export type SettingSection = "general" | "hotkeys" | "session" | "audio" | "output" | "transcription" | "polish" | "storage" | "metrics" | "privacy" | "updates";

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: SettingSectionSpec, settings section label, section order, Settings page sections
 *  * WHAT:  One Settings page section: which section and the heading it shows. The registry lists them in page order.
 *  * WHY:   The page renders a card per section from the registry (04 §5) and never spells a heading itself, so a new
 *  *        section is one registry entry with no UI change.
 *  * WHERE: registry/settings/sections.rs (SECTIONS); sent to the UI in RegistryView.sections.
 *  
 */
export type SettingSectionSpec = {
	section: SettingSection,
	label: string,
};

/**  A registry setting entry. */
export type SettingSpec = {
	key: SettingKey,
	section: SettingSection,
	label: string,
	help: string,
	kind: SettingKind,
	default: SettingValue,
	/**  A change applies only after Echo restarts. */
	restart_required: boolean,
	/**  Shown on the Settings page. False for internal state kept as a setting (e.g. onboarding completion). */
	visible: boolean,
	/**  The setting is hidden unless the requirement holds. */
	requires: CapsRequirement | null,
};

/**  The unit an `Int` setting is stored in, so the UI can label and format it without knowing the key. */
export type SettingUnit = "milliseconds" | "minutes" | "days" | "words_per_minute";

/**  The value of a setting. The `kind` tag always equals the `kind` of the setting's spec. */
export type SettingValue = { kind: "bool"; value: boolean } | { kind: "int"; value: number } | { kind: "enum"; value: string } | { kind: "hotkey"; value: string } | { kind: "device"; value: string | null } | { kind: "text"; value: string } | { kind: "pairs"; value: TextPair[] };

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: SettingsAvailability, settings_availability output, caps held, offered options, runtime options view
 *  * WHAT:  What the Settings page may offer right now: the caps requirements that hold, and the options of every
 *  *        `Enum` setting (fixed lists filtered by caps, runtime sources resolved against the current settings).
 *  * WHY:   Visibility and choices depend on the active adapters and the selected engine, which only Rust knows. The
 *  *        UI hides a setting whose requirement is missing and builds its Zod enum from exactly these options, and
 *  *        `settings_set` refuses anything outside them, so the form and the write check read one answer. Options of
 *  *        another setting can change after a write (a new engine brings its own languages), so the UI reads this
 *  *        again on SettingsChanged instead of computing it.
 *  * WHERE: Output of `settings_availability` (ipc/commands/settings.rs), built by `registry::settings::availability`.
 *  
 */
export type SettingsAvailability = {
	caps: CapsRequirement[],
	options: SettingOptions[],
};

/**  A setting was written or reset; `value` is the effective value after the change. */
export type SettingsChanged = {
	key: SettingKey,
	value: SettingValue,
};

export type SettingsResetInput = {
	key: SettingKey,
};

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: SettingsSetInput, SettingsResetInput, settings command input, garde schema, setting key rule
 *  * WHAT:  The inputs of `settings_set` (key and new value) and `settings_reset` (key).
 *  * WHY:   The factory enforces the declared garde schema before the handler runs (02 §4.1): a malformed key is a
 *  *        `Validation` error on `key`. The value is checked against the registry spec of that key (kind, bounds,
 *  *        runtime options) by `registry::settings::validate` in the handler, because which rule applies depends on
 *  *        the key and the current settings, which a static schema cannot see (02 §7.2); garde skips it for that
 *  *        reason only.
 *  * WHERE: ipc/commands/settings.rs; built in the UI through the generated bindings.
 *  
 */
export type SettingsSetInput = {
	key: SettingKey,
	value: SettingValue,
};

/**  A SHA-256 digest as 64 lowercase hex characters. */
export type Sha256Hex = string;

/**  A key combination in accelerator syntax, e.g. `Ctrl+Alt+Space`. Parsed only by the hotkey adapter. */
export type Shortcut = string;

/**  What the speech engine is doing and, once one is ready, where it runs and why. */
export type SpeechEngineStatus = {
	readiness: AsrReadiness,
	/**  Where the ready engine runs; None while no engine is ready. */
	accelerator: AcceleratorChoice | null,
};

/**  One entry of a `Pairs` setting, e.g. a dictionary replacement. */
export type TextPair = {
	from: string,
	to: string,
};

/**  The `general.theme` choice: follow Windows, or always light or dark. */
export type ThemePreference = "system" | "light" | "dark";

/**  One take in full. */
export type Transcript = {
	id: TranscriptId,
	created_at: UnixMs,
	status: TranscriptStatus,
	/**  Joined ASR output before polish. */
	raw_text: string | null,
	/**  Delivered text after the polish chain. */
	final_text: string | null,
	/**  The WAV journal is still on disk, so the take can be retried. */
	has_audio: boolean,
	duration_ms: number | null,
	/**  Speech time as detected by VAD, used for speaking WPM. */
	speech_ms: number | null,
	word_count: number | null,
	engine_id: EngineId | null,
	/**  Polishers that ran, in chain order. */
	polisher_ids: EngineId[],
	language: Language | null,
	/**  Stop → delivered, in milliseconds. */
	latency_ms: number | null,
	app_name: string | null,
	error_code: AppErrorCode | null,
};

/**  Primary key of one take: a ULID, so ids sort by creation time. */
export type TranscriptId = string;

/**
 * 
 *  * SOURCE OF TRUTH KEYWORDS: TranscriptInput, transcript id input, history_get, history_copy, history_delete, session_retry input
 *  * WHAT:  The input of every command that acts on one stored take: its id.
 *  * WHY:   One shape for get, copy, delete and retry, so a new per-take command (export, share) takes the same input.
 *  *        A struct, not a bare id, so a command can grow options without changing its call sites. The id is a ULID
 *  *        that serde already refuses when malformed (W27: the factory maps that to `Validation`), so garde has
 *  *        nothing left to check.
 *  * WHERE: ipc/commands/history.rs, ipc/commands/session.rs (`session_retry`); built in the UI by the History
 *  *        actions.
 *  
 */
export type TranscriptInput = {
	id: TranscriptId,
};

/**  A take was written to history. */
export type TranscriptSaved = TranscriptSummary;

/**  Lifecycle of a stored take; the wire form equals the `transcripts.status` column value. */
export type TranscriptStatus = 
/**  Row inserted, audio being captured. */
"recording" | 
/**  Capture finished, ASR or polish running. */
"transcribing" | "done" | 
/**  No speech was detected; nothing was pasted. */
"empty" | "failed" | 
/**  Found unfinished at startup; the WAV was repaired and can be retried (02 §7.3). */
"recoverable";

/**  One history list row. */
export type TranscriptSummary = {
	id: TranscriptId,
	created_at: UnixMs,
	status: TranscriptStatus,
	/**  Start of the final text, trimmed for the list; None until the take is transcribed. */
	preview: string | null,
	duration_ms: number | null,
	word_count: number | null,
	/**  Executable name of the app the text was delivered to. */
	app_name: string | null,
	error_code: AppErrorCode | null,
	has_audio: boolean,
};

/**  Whether Windows "Transparency effects" are on (05 W17). */
export type Transparency = "full" | 
/**  Transparency effects are off: every glass tint switches to its solid value. */
"reduced";

/**  Milliseconds since the Unix epoch (UTC). */
export type UnixMs = number;

/**  Result of an update check. */
export type UpdateStatus = 
/**  No update source exists in this build; nothing was checked. */
{ kind: "not_configured" } | { kind: "up_to_date" } | { kind: "available"; 
/**  SemVer of the newer release. */
version: string; 
/**  Release notes, when the source provides them. */
notes: string | null };

/**  Caps of an `Updater` adapter. */
export type UpdaterCaps = {
	/**  Updates can be checked and installed; false hides every update control (02 §11). */
	available: boolean,
};

/**  Caps of a `VoiceActivity` adapter. */
export type VadCaps = {
	/**  Length of the frame `push` expects, in milliseconds of 16 kHz audio. */
	frame_ms: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

