/**
 * SOURCE OF TRUTH KEYWORDS: bindings.ts, generated IPC bindings, tauri-specta, commands, events, AppError type
 * WHAT:  GENERATED by tauri-specta from the Rust types and commands. Never edit this file.
 * WHY:   The UI never hand-writes an IPC type; change the Rust type in src-tauri/src/types/ instead.
 * WHERE: Regenerated by `cargo test` (src-tauri/src/app/bindings.rs); imported as `@/bindings`.
 */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Every registry list the UI renders from. Compiled in, so it never changes while the app runs. */
	registryGet: () => typedError<RegistryView, AppError>(__TAURI_INVOKE("registry_get")),
};

/** Events */
export const events = {
	audioLevel: makeEvent<AudioLevel>("AudioLevel"),
	historyChanged: makeEvent<HistoryChanged>("HistoryChanged"),
	metricsChanged: makeEvent<MetricsChanged>("MetricsChanged"),
	modelProgress: makeEvent<ModelProgress>("ModelProgress"),
	sessionStateChanged: makeEvent<SessionStateChanged>("SessionStateChanged"),
	settingsChanged: makeEvent<SettingsChanged>("SettingsChanged"),
	transcriptSaved: makeEvent<TranscriptSaved>("TranscriptSaved"),
};

/* Types */
/**  Where inference runs. `gpu` means any DX12 adapter (DirectML), not one vendor. */
export type Accelerator = "cpu" | "gpu";

/**  Words delivered on one local calendar day. */
export type ActivityDay = {
	/**  Local date as `YYYY-MM-DD`. */
	date: string,
	words: number,
};

/**  The only error type that crosses IPC. The variant name is the stable wire `code`. */
export type AppError = { code: "Validation"; field: string; message: string } | { code: "PermissionDenied"; permission: Permission } | { code: "Busy" } | { code: "NotFound"; resource: ResourceKind } | { code: "ModelMissing"; model_id: ModelId } | { code: "ModelCorrupt"; model_id: ModelId } | { code: "AudioDevice" } | { code: "Asr" } | { code: "Polish" } | { code: "Storage" } | { code: "Offline" } | { code: "Network" } | { code: "Hotkey"; reason: HotkeyIssue } | { code: "Internal" };

/**  The stable code of an AppError variant, without its fields. */
export type AppErrorCode = "Validation" | "PermissionDenied" | "Busy" | "NotFound" | "ModelMissing" | "ModelCorrupt" | "AudioDevice" | "Asr" | "Polish" | "Storage" | "Offline" | "Network" | "Hotkey" | "Internal";

/**  Caps of an `AsrEngine` adapter. */
export type AsrCaps = {
	languages: Language[],
	/**  The engine detects the spoken language itself. */
	auto_language: boolean,
	/**  Output already carries punctuation. */
	punctuation: boolean,
	/**  Output already carries sentence casing, so the rule polisher skips its casing stage. */
	casing: boolean,
	accelerators: Accelerator[],
	/**  Longest audio segment the engine accepts in one `transcribe` call, in seconds. */
	max_segment_s: number,
};

/**  Caps of an `AudioCapture` adapter. */
export type AudioCaps = {
	/**  Device sample rates the adapter can open, in Hz. */
	sample_rates: number[],
	/**  Channel counts the adapter can open. */
	channels: number[],
};

/**  An audio input device the user can pick in Settings. */
export type AudioDevice = {
	id: AudioDeviceId,
	/**  Name as Windows shows it, e.g. `Microphone (USB Audio)`. */
	name: string,
	/**  Windows currently uses this device as the default input. */
	is_default: boolean,
};

/**  Stable id of an audio input device as its capture adapter reports it; stored by `audio.input_device`. */
export type AudioDeviceId = string;

/**  Input level while recording, at most 30 Hz. */
export type AudioLevel = {
	/**  Root mean square of the last frame, 0 to 1. */
	rms: number | null,
};

/**  A size or transfer amount in bytes. */
export type ByteCount = number;

/**  A capability the active adapters must declare for a setting or option to be shown. */
export type CapsRequirement = 
/**  The active ASR engine lists `gpu` in `AsrCaps.accelerators`. */
"gpu_accelerator" | 
/**  The active ASR engine lists more than one language. */
"multiple_languages" | 
/**  The hotkey adapter reports key-up (`HotkeyCaps.supports_release`), needed for hold-to-talk. */
"hotkey_release" | 
/**  The updater adapter reports `UpdaterCaps.available`. */
"updater_available";

/**  How a finished take reached the user. */
export type DeliveryOutcome = 
/**  Pasted into the target app (and kept on the clipboard if the setting is on). */
"pasted" | 
/**  Only copied: the target could not receive a paste (elevated window, 05 W2) or auto-paste is off. */
"copied" | 
/**  VAD heard no speech; nothing was pasted (02 §6.1, 05 A4). */
"no_speech";

/**  The caps a registry engine entry declares, tagged by the kind of engine it builds. */
export type EngineCaps = {
	kind: "asr",
} & AsrCaps | {
	kind: "polisher",
} & PolisherCaps | {
	kind: "vad",
} & VadCaps;

/**  Registry id of an engine entry (ASR, polisher or VAD), kebab-case, e.g. `parakeet-tdt-0.6b-v3`. */
export type EngineId = string;

/**  What an engine registry entry builds. */
export type EngineKind = "asr" | "polisher" | "vad";

/**  What the UI (Models page, Settings options) knows about a registry engine entry. */
export type EngineSpec = {
	id: EngineId,
	label: string,
	/**  The model manifest the engine runs, when it needs one. */
	model_id: ModelId | null,
	caps: EngineCaps,
};

/**  One choice of an `Enum` setting. */
export type EnumOption = {
	/**  Stored value. */
	value: string,
	label: string,
	/**  The option is hidden unless the requirement holds. */
	requires: CapsRequirement | null,
};

/**  The options of an `Enum` setting: a fixed list, or a source resolved at runtime by the registry. */
export type EnumOptions = { from: "fixed"; list: EnumOption[] } | { from: "runtime"; source: OptionSource };

/**  Why the history list changed. */
export type HistoryChangeReason = "inserted" | "updated" | "deleted" | 
/**  Startup recovery marked unfinished takes recoverable. */
"recovered" | 
/**  A retention sweep removed audio or rows. */
"retention";

/**  History rows changed; list queries should refetch. */
export type HistoryChanged = {
	reason: HistoryChangeReason,
};

/**  Caps of a `HotkeyService` adapter. */
export type HotkeyCaps = {
	/**  Key-up events are reported, so hold-to-talk is possible. */
	supports_release: boolean,
	/**  A combination of modifiers alone (e.g. Ctrl+Alt) can be bound. */
	supports_modifier_only: boolean,
};

/**  Registry id of a hotkey binding, kebab-case, e.g. `record`, `paste-last`, `cancel`. */
export type HotkeyId = string;

/**  Why a hotkey could not be registered. */
export type HotkeyIssue = 
/**  Another app already owns the combination (05 W7). */
"conflict" | 
/**  The combination cannot be registered (no key, or not allowed by the hotkey adapter's caps). */
"invalid";

/**  When a hotkey is registered with the system. */
export type HotkeyScope = 
/**  From startup until exit. */
"always" | 
/**  Only while a take is recording or counting down to cancel. */
"during_session";

/**  A registry hotkey entry. */
export type HotkeySpec = {
	id: HotkeyId,
	label: string,
	default_accelerator: Shortcut,
	/**  The Hotkey setting the user rebinds it with; None when the combination is fixed. */
	setting_key: SettingKey | null,
	scope: HotkeyScope,
};

/**  Caps of a `TextInserter` adapter. */
export type InserterCaps = {
	/**  Can paste into windows running at a higher integrity level than Echo (05 W2). */
	can_target_elevated: boolean,
	/**  Inserts by pasting what the clipboard holds, so delivery writes the text to the clipboard first. */
	uses_clipboard: boolean,
};

/**
 *  A spoken-language code (ISO 639-1, e.g. `en`, `de`). "Auto-detect" is not a language; it is the absence
 *  of one (`Option<Language>`), offered only when `AsrCaps.auto_language` is set.
 */
export type Language = string;

/**  Which spoken languages a component handles. */
export type LanguageSupport = { kind: "any" } | { kind: "only"; languages: Language[] };

/**  How much latency a polisher adds to delivery. */
export type LatencyClass = 
/**  Milliseconds; always safe on the delivery path. */
"instant" | 
/**  Hundreds of milliseconds; must run under a timeout with a fallback (02 §8.3). */
"slow";

/**  The SQL aggregate behind a metric (formulas in 02 §7.4). */
export type MetricAggregate = "words" | "transcriptions" | "time_saved" | "speaking_wpm" | "median_latency" | "streak";

/**  Where a metric sits on the dashboard (04 §5). */
export type MetricEmphasis = 
/**  The one large card at the top. */
"hero" | 
/**  A regular stat card, or the activity chart for an `activity` query. */
"primary" | 
/**  A small card below the chart. */
"secondary";

/**  Registry id of a dashboard metric, kebab-case, e.g. `time-saved`. */
export type MetricId = string;

/**  What a metric reads. */
export type MetricQuery = 
/**  One value of `metrics_summary(range)`. */
{ kind: "summary"; aggregate: MetricAggregate } | 
/**  Words per day for the last `days` days, from `metrics_activity(days)`. */
{ kind: "activity"; days: number };

/**  A registry metric entry. */
export type MetricSpec = {
	id: MetricId,
	label: string,
	/**  One sentence on how the value is computed, shown as the card's tooltip. */
	help: string,
	unit: MetricUnit,
	query: MetricQuery,
	emphasis: MetricEmphasis,
};

/**  How a metric value is formatted. */
export type MetricUnit = 
/**  Milliseconds shown as a human duration (e.g. `2 h 5 min`). */
"duration" | "count" | "wpm" | 
/**  Milliseconds shown as-is (latency). */
"ms" | "days";

export type MetricValue = {
	aggregate: MetricAggregate,
	/**  None when there is no completed take in the range. */
	value: number | null,
};

/**  Dashboard aggregates changed; metric queries should refetch. */
export type MetricsChanged = Record<string, never>;

/**  The window a summary covers, ending now. */
export type MetricsRange = "today" | "last_7_days" | "last_30_days" | "all_time";

export type MetricsSummary = {
	range: MetricsRange,
	values: MetricValue[],
};

/**  One file of a model. */
export type ModelFile = {
	/**  File name inside the model folder, e.g. `encoder-model.int8.onnx`; never a path with separators. */
	name: string,
	/**  Where it is downloaded from; for a bundled model, the upstream it was taken from. */
	url: string,
	sha256: Sha256Hex,
	bytes: ByteCount,
};

/**  Registry id of a model manifest, kebab-case. */
export type ModelId = string;

/**  Everything needed to fetch, verify and credit a model. */
export type ModelManifest = {
	id: ModelId,
	label: string,
	/**  SPDX license id, e.g. `CC-BY-4.0`, listed in About → Models & licenses (05 A15). */
	license: string,
	/**  Credit line the license requires; None when it requires none. */
	attribution: string | null,
	/**  Upstream revision (commit hash) the digests were computed from. */
	revision: string,
	files: ModelFile[],
	/**  Ships inside the installer's resources, so it is never downloaded. */
	bundled: boolean,
};

export type ModelPhase = 
/**  Bytes are arriving from the network or being copied from the chosen folder. */
"transferring" | 
/**  SHA-256 of every file is being checked. */
"verifying" | 
/**  Verified files are being moved into `models/<id>/`. */
"installing" | 
/**  The model is installed and usable. */
"ready" | "cancelled" | "failed";

/**  Progress of a model download or import, at most 10 Hz. */
export type ModelProgress = {
	model_id: ModelId,
	bytes: ByteCount,
	total: ByteCount,
	phase: ModelPhase,
};

/**  Whether a model is on disk and usable. */
export type ModelStatus = { kind: "not_installed" } | 
/**  An interrupted download left `bytes` in the `.partial` folder; the next download resumes from there. */
{ kind: "partial"; bytes: ByteCount } | 
/**  Every file is in place with the manifest's size (hashes are checked on demand, 02 §8.2). */
{ kind: "installed" };

/**  A sidebar icon, serialized as its lucide-react name (e.g. `layout-dashboard`). */
export type NavIcon = "layout-dashboard" | "history" | "boxes" | "settings";

/**  Registry id of a sidebar navigation item, kebab-case, e.g. `dashboard`. */
export type NavId = string;

/**  A registry navigation entry. */
export type NavItem = {
	id: NavId,
	label: string,
	icon: NavIcon,
	/**  Router path, starting with `/`. */
	route: string,
	/**  Position in the sidebar, ascending; unique across entries. */
	order: number,
};

/**  Where the options of an `Enum` setting come from when they depend on what is registered or installed. */
export type OptionSource = 
/**  Every registered engine of kind `asr`. */
"asr_engines" | 
/**  Registered polisher engines that need a model (the opt-in LLM stage; the always-on rule stages need none). */
"model_polishers" | 
/**  `auto` (when the selected ASR engine auto-detects) plus every language of that engine. */
"asr_languages" | 
/**  `auto` plus every accelerator of the selected ASR engine. */
"asr_accelerators";

/**  A slice of a longer list, newest first unless the command says otherwise. */
export type Page<T> = {
	items: T[],
	/**  None when this is the last page. */
	next_cursor: PageCursor | null,
};

/**  Opaque position after the last item of a page; pass it back to fetch the next page. */
export type PageCursor = string;

export type Permission = 
/**  Windows microphone privacy consent for desktop apps. */
"microphone" | 
/**  Any outbound request; offline mode denies it. */
"network" | 
/**  Reading or writing the system clipboard. */
"clipboard" | 
/**  Sending synthetic input (the Ctrl+V paste) to the focused app. */
"input_injection";

/**  Whether a permission holds right now. */
export type PermissionState = "granted" | "denied";

/**  Caps of a `TextPolisher` adapter. */
export type PolisherCaps = {
	latency_class: LatencyClass,
	languages: LanguageSupport,
	/**  A model must be installed before the polisher can run. */
	needs_model: boolean,
};

/**  Every registry list the UI renders from. */
export type RegistryView = {
	settings: SettingSpec[],
	hotkeys: HotkeySpec[],
	nav: NavItem[],
	engines: EngineSpec[],
	metrics: MetricSpec[],
};

/**  What a `NotFound` error could not find. */
export type ResourceKind = "transcript" | "model" | "engine" | "setting" | "audio_device" | 
/**  An update to install (the updater found none, or updates are not configured, 02 §11). */
"update";

/**  The session changed state; carries the full view, so the UI never merges partial updates. */
export type SessionStateChanged = SessionView;

/**  Where a take is in its lifecycle (02 §5 diagram). */
export type SessionStatus = "idle" | 
/**  Hotkey pressed: the row is inserted and the mic is opening. */
"arming" | "recording" | 
/**  Esc pressed: capture paused while the cancel countdown runs. */
"cancel_pending" | 
/**  Capture stopped: tail ASR, segment join and polish are running. */
"finalizing" | 
/**  Text is going to the clipboard and the target app. */
"delivering" | "done" | 
/**  The countdown elapsed: row and audio were deleted. */
"discarded" | 
/**  The take failed; its audio and row are kept for retry. */
"failed";

/**  Session inputs the UI is allowed to send through `session_input`. */
export type SessionUiInput = 
/**  The pill's stop button: same effect as pressing the record hotkey while recording. */
"stop";

/**  Everything the UI may know about the current take. */
export type SessionView = {
	status: SessionStatus,
	/**  The take's row, once it exists (from `Arming` on). */
	transcript_id: TranscriptId | null,
	/**  Recorded time so far, excluding time paused in `CancelPending`. */
	elapsed_ms: number,
	/**  Time left before a pending cancel discards the take. */
	countdown_remaining_ms: number | null,
	/**  Set when `status` is `Done`. */
	outcome: DeliveryOutcome | null,
	/**  Set when `status` is `Failed`. */
	error: AppError | null,
};

/**  Registry key of a setting, `section.snake_key`, e.g. `output.auto_paste`. */
export type SettingKey = string;

/**  The control and the validation rule of a setting. */
export type SettingKind = { kind: "bool" } | 
/**  Inclusive range. */
{ kind: "int"; min: number; max: number; unit: SettingUnit | null } | { kind: "enum"; options: EnumOptions } | 
/**  A global shortcut accelerator such as `Ctrl+Alt+Space`; only the hotkey adapter parses it. */
{ kind: "hotkey" } | 
/**
 *  An audio input device id; no value means the system default device. Its options are the devices the
 *  capture adapter lists at runtime (`audio_list_devices`).
 */
{ kind: "device" } | { kind: "text"; max_len: number } | { kind: "pairs"; max_pairs: number; max_len: number };

/**  The Settings page group a setting belongs to; equals the prefix of its key (`general.theme` → `general`). */
export type SettingSection = "general" | "hotkeys" | "session" | "audio" | "output" | "transcription" | "polish" | "storage" | "metrics" | "privacy" | "updates";

/**  A registry setting entry. */
export type SettingSpec = {
	key: SettingKey,
	section: SettingSection,
	label: string,
	help: string,
	kind: SettingKind,
	default: SettingValue,
	/**  A change applies only after Echo restarts. */
	restart_required: boolean,
	/**  Shown on the Settings page. False for internal state kept as a setting (e.g. onboarding completion). */
	visible: boolean,
	/**  The setting is hidden unless the requirement holds. */
	requires: CapsRequirement | null,
};

/**  The unit an `Int` setting is stored in, so the UI can label and format it without knowing the key. */
export type SettingUnit = "milliseconds" | "minutes" | "days" | "words_per_minute";

/**  The value of a setting. The `kind` tag always equals the `kind` of the setting's spec. */
export type SettingValue = { kind: "bool"; value: boolean } | { kind: "int"; value: number } | { kind: "enum"; value: string } | { kind: "hotkey"; value: string } | { kind: "device"; value: string | null } | { kind: "text"; value: string } | { kind: "pairs"; value: TextPair[] };

/**  A setting was written or reset; `value` is the effective value after the change. */
export type SettingsChanged = {
	key: SettingKey,
	value: SettingValue,
};

/**  A SHA-256 digest as 64 lowercase hex characters. */
export type Sha256Hex = string;

/**  A key combination in accelerator syntax, e.g. `Ctrl+Alt+Space`. Parsed only by the hotkey adapter. */
export type Shortcut = string;

/**  One entry of a `Pairs` setting, e.g. a dictionary replacement. */
export type TextPair = {
	from: string,
	to: string,
};

/**  One take in full. */
export type Transcript = {
	id: TranscriptId,
	created_at: UnixMs,
	status: TranscriptStatus,
	/**  Joined ASR output before polish. */
	raw_text: string | null,
	/**  Delivered text after the polish chain. */
	final_text: string | null,
	/**  The WAV journal is still on disk, so the take can be retried. */
	has_audio: boolean,
	duration_ms: number | null,
	/**  Speech time as detected by VAD, used for speaking WPM. */
	speech_ms: number | null,
	word_count: number | null,
	engine_id: EngineId | null,
	/**  Polishers that ran, in chain order. */
	polisher_ids: EngineId[],
	language: Language | null,
	/**  Stop → delivered, in milliseconds. */
	latency_ms: number | null,
	app_name: string | null,
	error_code: AppErrorCode | null,
};

/**  Primary key of one take: a ULID, so ids sort by creation time. */
export type TranscriptId = string;

/**  A take was written to history. */
export type TranscriptSaved = TranscriptSummary;

/**  Lifecycle of a stored take; the wire form equals the `transcripts.status` column value. */
export type TranscriptStatus = 
/**  Row inserted, audio being captured. */
"recording" | 
/**  Capture finished, ASR or polish running. */
"transcribing" | "done" | 
/**  No speech was detected; nothing was pasted. */
"empty" | "failed" | 
/**  Found unfinished at startup; the WAV was repaired and can be retried (02 §7.3). */
"recoverable";

/**  One history list row. */
export type TranscriptSummary = {
	id: TranscriptId,
	created_at: UnixMs,
	status: TranscriptStatus,
	/**  Start of the final text, trimmed for the list; None until the take is transcribed. */
	preview: string | null,
	duration_ms: number | null,
	word_count: number | null,
	/**  Executable name of the app the text was delivered to. */
	app_name: string | null,
	error_code: AppErrorCode | null,
	has_audio: boolean,
};

/**  Milliseconds since the Unix epoch (UTC). */
export type UnixMs = number;

/**  Result of an update check. */
export type UpdateStatus = 
/**  No update source exists in this build; nothing was checked. */
{ kind: "not_configured" } | { kind: "up_to_date" } | { kind: "available"; 
/**  SemVer of the newer release. */
version: string; 
/**  Release notes, when the source provides them. */
notes: string | null };

/**  Caps of an `Updater` adapter. */
export type UpdaterCaps = {
	/**  Updates can be checked and installed; false hides every update control (02 §11). */
	available: boolean,
};

/**  Caps of a `VoiceActivity` adapter. */
export type VadCaps = {
	/**  Length of the frame `push` expects, in milliseconds of 16 kHz audio. */
	frame_ms: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

